name: PR Checks

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  release-label:
    name: Release note label
    runs-on: ubuntu-latest

    steps:
      - name: Check minimum labels
        uses: mheap/github-action-required-labels@d25134c992b943fb6ad00c25ea00eb5988c0a9dd # v5.4.2
        with:
          mode: minimum
          count: 1
          labels: |
            release-note/ignore
            kind/feature
            release-note/feature
            kind/bug
            release-note/bug-fix
            release-note/breaking-change
            release-note/deprecation
            area/dependencies
            release-note/dependency-update
            kind/refactor
            release-note/misc
            kind/documentation
