name: Node SDK

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/openapi.yaml
      - .github/workflows/sdk-node.yaml

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.head_ref }}

      - name: Generate
        uses: dagger/dagger-for-github@158efd19b6af5ff000289d6c7c507ada3c7b3b9b # v5.8.0
        with:
          verb: call
          args: --source .:default generate node-sdk -o api/client/node
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.11.7"

      - name: Open pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: openapi/node-sdk
          branch-suffix: short-commit-hash
          delete-branch: true
          commit-message: "chore(api): generate node client"
          title: "[bot] Re-generate Node.js client"
          body: "This PR was automatically generated."
          labels: |
            area/api
            release-note/misc
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
