name: Web SDK

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/openapi.yaml
      - .github/workflows/sdk-web.yaml

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.head_ref }}

      - name: Generate
        uses: dagger/dagger-for-github@eba69b4dddb54eddfdb51a88eb7fd86957137630 # v5.4.0
        with:
          verb: call
          args: --source .:default generate web-sdk -o api/client/web
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.11.3"

      - name: Open pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: openapi/web-sdk
          branch-suffix: short-commit-hash
          delete-branch: true
          commit-message: "chore(api): generate web client"
          title: "[bot] Re-generate Web client"
          body: "This PR was automatically generated."
          labels: |
            area/api
            release-note/misc
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
