name: Python SDK

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/openapi.yaml
      - .github/workflows/sdk-python.yaml

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{ github.head_ref }}

      - name: Generate
        uses: dagger/dagger-for-github@53a90075b0001a5d43da1f8bb5f3b6dba9c33c74 # v5.6.0
        with:
          verb: call
          args: --source .:default generate python-sdk -o api/client/python
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.11.4"

      - name: Open pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: openapi/python-sdk
          branch-suffix: short-commit-hash
          delete-branch: true
          commit-message: "chore(api): generate python client"
          title: "[bot] Re-generate Python client"
          body: "This PR was automatically generated."
          labels: |
            area/api
            release-note/misc
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
