name: Snapshot

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: dagger/dagger-for-github@53a90075b0001a5d43da1f8bb5f3b6dba9c33c74 # v5.6.0
        with:
          verb: call
          module: github.com/${{ github.repository }}@${{ github.ref }}
          args: --ref ${{ github.ref }} snapshot --stainless-token env:STAINLESS_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.11.4"
        env:
          STAINLESS_TOKEN: ${{ secrets.STAINLESS_TOKEN }}
