name: Snapshot

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: dagger/dagger-for-github@a3c3f2627ad38ef0b9334ef70dcd6a0e4617d2a7 # v5.9.0
        with:
          verb: call
          module: github.com/${{ github.repository }}@${{ github.ref }}
          args: --ref ${{ github.ref }} snapshot --stainless-token env:STAINLESS_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.11.7"
        env:
          STAINLESS_TOKEN: ${{ secrets.STAINLESS_TOKEN }}
