name: Trivy

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Mirror Trivy database
        run: skopeo --insecure-policy copy --all --retry-times 10 docker://ghcr.io/aquasecurity/trivy-db:2 docker://ghcr.io/openmeterio/trivy-db:2
